### ISSUE TITLE
Accessibility volunteering certificate

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/vca-asm#57]
During the first version of the Pool², the volunteering certificate has to be created by the Pool 1. To do so, it is required to implement a route generating the certificate by the session's user. Thus, it is possible to create  link in the Pool² UI.

**Comment by TobiKaestle** [comment]
When logged in, the certificate can be downloaded via
https://vca.informatik.hu-berlin.de/pool/?download-certificate
