### ISSUE TITLE
Header and footer as widgets

### ISSUE THREAD

**Issue by johannsell** [Viva-con-Agua/vca-asm#65]
Precondition: [Dispenser #44](https://github.com/Viva-con-Agua/dispenser/issues/44)

Replace the header and footer by widgets prepared by the Pool². Use [dispenser_navigation_widget](https://github.com/Viva-con-Agua/dispenser_navigation_widget) to replace the header. When [Dispenser #44](https://github.com/Viva-con-Agua/dispenser/issues/44) is done, also the footer has to be replaced.

**Comment by TobiKaestle** [comment]
Added the header and footer widget to the old pool, disabled top navigation and removed footer styles.
Pool-theme styles still have side-effects on header and footer. Will fix this when style of header and footer is finished
